#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmakeLnInclude decompositionMethods
wmakeLnInclude metisDecomp
wmakeLnInclude parmetisDecomp
wmakeLnInclude scotchDecomp
wmakeLnInclude ptscotchDecomp

#------------------------------------------------------------------------------
